name: Pull Requests

on:
  pull_request:
    branches: [main]
    types: [opened]
    paths:
      - 'data/members.json'
  push:
    branches:
      - 'feature/github-actions'
    paths:
    - 'data/members.json'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    name: "Check changes files"
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          URLS=$(git diff origin/main..HEAD --unified=0 -- ./data/members.json | grep '"url"'  | grep -o '\"url\":\s\".*\"' | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | sort -u)
          for url in $URLS; do\
            echo "Looking at $url"\
            curl -s $url | grep -qo "<the-claw-webring-widget>"\
            if [ $? -eq 0 ]; then\
              echo "The <the-claw-webring-widget> tag was found in $url"\
            else\
              echo "The <the-claw-webring-widget> tag was not found in $url"\
              exit -1\
            fi\
          done\
          \
          echo "Finished searching for and it passed"\
          exit 0\
